### ISSUE TITLE
Default test suite fails with Runtime Error

### ISSUE THREAD

**Issue by jorihardman** [wbkd/react-starterkit#6]
Hello,

I just cloned this, and the only thing I've done is run ```npm install```

```npm start``` serves a working example app.

However, ```npm test``` fails with the following:

```
> npm test

> webkid-react-starterkit@1.0.1 test Code/company/web_frontend
> jest

Using Jest CLI v0.7.1
 PASS  app/scripts/__tests__/header-test.js (0.347s)
 FAIL  app/scripts/__tests__/itemlist-test.js
● Runtime Error
TypeError: Code/company/web_frontend/app/scripts/__tests__/itemlist-test.js: Code/company/web_frontend/node_modules/react/react.js: Code/company/web_frontend/node_modules/react/lib/React.js: Code/company/web_frontend/node_modules/react/lib/ReactDOM.js: Code/company/web_frontend/node_modules/react/lib/ReactDOMTextComponent.js: Code/company/web_frontend/node_modules/react/lib/ReactComponentBrowserEnvironment.js: Code/company/web_frontend/node_modules/react/lib/ReactDOMIDOperations.js: Code/company/web_frontend/node_modules/react/lib/ReactMount.js: Code/company/web_frontend/node_modules/react/lib/ReactElement.js: Cannot read property 'type' of null
    at makeComponent (Code/company/web_frontend/node_modules/jest-cli/src/lib/moduleMocker.js:161:15)
    at generateMock (Code/company/web_frontend/node_modules/jest-cli/src/lib/moduleMocker.js:280:16)
    at Object.generateFromMetadata (Code/company/web_frontend/node_modules/jest-cli/src/lib/moduleMocker.js:308:16)
    at Loader._generateMock (Code/company/web_frontend/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:277:25)
    at Loader.requireMock (Code/company/web_frontend/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:757:45)
    at Loader.requireModuleOrMock (Code/company/web_frontend/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:873:19)
    at Object.<anonymous> (Code/company/web_frontend/node_modules/react/lib/ReactElement.js:17:25)
    at Object.runContentWithLocalBindings (Code/company/web_frontend/node_modules/jest-cli/src/lib/utils.js:397:17)
    at Loader._execModule (Code/company/web_frontend/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:234:11)
    at Loader.requireModule (Code/company/web_frontend/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:845:14)
npm ERR! Test failed.  See above for more details.
```

**Comment by g-div** [comment]
Strange...I'm unable to reproduce the problem. 

Which version of node and OS are you using ?
Is `npm start` working ?

**Comment by jorihardman** [comment]
Yes, npm start works just fine. I'm using node v5.1.0 on OSX 10.10.3.

Other people on my team using Linux were able to install and test with no problem, so it seems to be a mac issue.

**Comment by jorihardman** [comment]
Apparently this failure is due to having a space in the file path (thanks Dropbox). If I move the folder elsewhere it works fine.
